---
title: "Bachelorarbeit"
author: "Laura Kiemes, 12250912"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    number_sections: yes
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: '2'
---

# Setup

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

if (!require("pacman")) install.packages("pacman"); library(pacman)
pacman::p_load(devtools)
if (!require("stdidx")) devtools::install_github("graemeblair/stdidx"); library(stdidx)
pacman::p_load(haven, readr, tidyverse, gtsummary)

here::i_am("project.Rmd")
```

# Data Cleaning

```{r cleaning ZA4500_patch_v2-0-0.do}
allbus2006 <- read_dta(here::here("data", "ZA4500_v2-0-0.dta")) # gesis data

allbus2006 <- allbus2006 |> 
  mutate(
    split = case_when(v3 == 2 ~ 0,
                      TRUE ~ v3),
    split = factor(split,
                        levels = c(0, 1),
                        labels = c("CASI", "CAPI")),
    age = case_when(v27 == 999 ~ NA,
                      TRUE ~ v26),
    immigration_anpassen = case_when(v43 %in% c(1:7) ~ v43,
                              TRUE ~ NA),
    immigration_heim = case_when(v44 %in% c(1:7) ~ v44,
                              TRUE ~ NA),
    immigration_unpolit = case_when(v45 %in% c(1:7) ~ v45,
                              TRUE ~ NA),
    immigration_heirat = case_when(v46 %in% c(1:7) ~ v46,
                              TRUE ~ NA),
    immigration = idx_mean(immigration_anpassen, 
                           immigration_heim, 
                           immigration_unpolit, 
                           immigration_heirat),
    immigration_log = log(immigration),
    split_selbst = factor(v47,
                          levels = c(0:4),
                          labels = c("CAPI", 
                                     "ja, ohne Hilfe",
                                     "ja, Hilfe vorher",
                                     "ja, Hilfe dabei",
                                     "nein")),
    interviewer_male = case_when(v702 == 2 ~ 0, 
                                 TRUE ~ v702),
    interviewer_age = v703,
    interviewer_agediff = case_when(v703 == 999 ~ NA, 
                                    TRUE ~ abs(v703 - v27)),
    interviewer_edu = factor(v705,
                             levels = c(1:4), 
                             labels = c("Volks-/Hauptschulabschluss",
                                        "Mittlere Reife",
                                        "(Fach-)Hochschulreife",
                                        "(Fach-)Hochschulabschluss"),
                             ordered = TRUE)
    ) 
```

```{r save csv}
write_csv(allbus2006, here::here("data", "allbus2006.csv")) # save as csv
```



# Results

## Univariate Deskription

## Zentraler Zusammenhang

```{r}
ggplot(data = allbus2006, mapping = aes(x = split_selbst, y = immigration)) +
  geom_boxplot() 
```

# Linear Regression

## Unabhängigkeit

```{r}
cor(allbus2006 |> 
      select(
        interviewer_age,
        interviewer_agediff,
        age,
        immigration,
        immigration_log
      )) # all independant variables
```

## Normalverteilung

```{r}
hist(allbus2006$immigration_log)
hist(allbus2006$immigration)
```

## Einfache lineare Regression

```{r}
split_immigration.lm <- lm(immigration ~ split_selbst, data = allbus2006)

summary(split_immigration.lm)
```

## Multiple lineare Regression

```{r}
split_immigration_multiple.lm <- lm(immigration ~ split_selbst + age + interviewer_male + interviewer_agediff, data = allbus2006)

summary(split_immigration_multiple.lm)
```


## Homoskedaszität

```{r}
par(mfrow=c(2,2))
plot(split_immigration_multiple.lm)
par(mfrow=c(1,1))
```









